name: first workflow
on:
  workflow_dispatch:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: |
           echo "The following is a secret: ${{ secrets.GITHUBOVERVIEW_SECRET }}, of course, I cant tell you because then it wouldnt be a secret..."
           echo Hello World! This is the first job
      - name: Checkout
        uses: actions/checkout@v4.0.0
            
